---
title: "Thesis Tables and Figures"
author: "Justin Priest"
date: "May 1, 2019"
output: word_document
---
This document produces figures and tables for the report then outputs it to MS Word. 
The tables from the Word doc can then be copied into Excel for final formatting to remain consistent. 


```{r loading, echo = FALSE, results = FALSE, message = FALSE, warning=FALSE}
#Figures and Tables


library(corrplot)
library(knitr)
library(kableExtra)
library(here)
library(extrafont)
# font_import()  #this only needs to be run once
loadfonts(device="win") #change for mac users


# Later can make an RDA file to save output from all of these
source(here::here("Analysis/thesis2019_Ch1_2-speciesrichness.R"))
source(here::here("Analysis/thesis2019_Ch1_3-rarespecies.R"))
source(here::here("Analysis/thesis2019_Ch1_4-PERMANOVA.R"))
source(here::here("Analysis/thesis2019_Ch1_5-TimeSeries.R"))


# default report theme for ggplot, use by adding "+ report_theme()" to ggplot call
report_theme <- function() {
  theme_bw() + 
    theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), 
          text=element_text(family="Times New Roman", size=12), 
          axis.text.x = element_text(angle = 35, hjust = 1),  
          panel.border = element_blank(), 
          axis.line = element_line())
}


```


``` {r corrplot}
env.biwk.corr <- cor(pru.env.biwk %>% ungroup() %>% dplyr::select(-Year, -biweekly, -Station), use = "complete.obs")
env.ann.corr <- cor(pru.env.ann %>% ungroup() %>% dplyr::select(-Year,  -Station), use = "complete.obs")


corrplot.mixed(env.biwk.corr)
corrplot.mixed(env.ann.corr)

env.biwk.corr[upper.tri(env.biwk.corr)] <- 0
lower.tri(env.biwk.corr, diag = FALSE)
```



```{r Table1, echo = FALSE, message = FALSE, warning=FALSE}
# Total Catch Table
catchtable <- expand(catchenviron %>% group_by(Year, Station, biweekly),
       Species=unique(catchenviron$Species)) %>%# need this part to put in blank yr/stn/species catches
  left_join(catchenviron, 
            by = c("Species" = "Species", "Year" = "Year", "biweekly" = "biweekly", "Station" = "Station")) %>% 
  # this first part makes sure to add in blank Year/biweek combos for species which are not frequently caught
  filter(Species != "UNKN" & Species != "LIPA" & Species != "HYCS"  & Species != "ELPT") %>%
  group_by(Species, Year, biweekly, Station) %>% summarise(biwkCatch = sum(totcount)) %>% 
  mutate(biwkCatch = replace_na(biwkCatch, 0)) %>% #replace NAs with 0
  group_by(Species) %>% 
  summarise(TotalCatch = sum(biwkCatch), MeanCatch = mean(biwkCatch), 
            MinCatch = min(biwkCatch), MaxCatch = max(biwkCatch),
            PercentPresent = 1-(sum(if_else(biwkCatch == 0, 1, 0)) / 280)) %>% 
  # there were 280 combos of stns,biwks, yrs (did not fish 8 yr/stn/biwks)
  left_join(spplookup, by = c("Species" = "Species")) %>% ungroup() %>% 
  mutate(rarespecies = if_else(Species %in% keepspp, "*", "")) %>%
  dplyr::select(commonname, TotalCatch, MeanCatch, MinCatch, MaxCatch, PercentPresent, rarespecies) %>%
  arrange(commonname) %>% rename(Species = commonname) %>% 
  kableExtra::kable(format.args = list(big.mark = ","), digits = c(0, 0, 0, 0, 1, 3,0))

catchtable 

```


```{r permanovatables, echo = FALSE, message = FALSE, warning=FALSE}


data.frame(permanova.ann)

data.frame(permanova.biwk)

```





```{r envtimeseries}

catchenviron %>% group_by(Species) %>% summarise(sum(totcount)) %>% kable()

catchmatrix.biwk %>% mutate(numspp = rowSums(. >0)) %>% View()
catchmatrix.biwk %>% mutate(numspp = rowSums(. >0)) %>% summarise(mean(numspp))

pru.env.biwk %>% mutate(windspd.scale =scale(biwkmeanspeed_kph))

scaledenv.ann <- pru.env.ann %>% group_by(Year) %>% 
  summarise_at(vars(annwindspeed_kph:annwinddir_ew), mean, na.rm = TRUE) %>% #annual means, all stns included
  mutate_at(vars(annwindspeed_kph:annwinddir_ew), scale)

scaledenv.ann %>% dplyr::select(-annwinddir) %>% gather(key = "env_var", "scaled_value", -Year)

ggplot(scaledenv.ann %>% dplyr::select(-annwinddir) %>% gather(key = "env_var", "scaled_value", -Year), 
       aes(x=as.numeric(Year)+2000, y=scaled_value, color=env_var)) + geom_line(cex=1.5) +
  scale_x_continuous(breaks= seq(2001, 2018)) +
  labs(x="", y="Scaled value, mu=0, sd=1") + 
  report_theme()
  


  
scaledenv.ann.stn <- pru.env.ann %>% group_by(Year, Station) %>% 
  summarise_at(vars(annwindspeed_kph:annwinddir_ew), mean, na.rm = TRUE) %>% #annual means, all stns included
  mutate_at(vars(annwindspeed_kph:annwinddir_ew), scale)

ggplot(scaledenv.ann.stn %>% dplyr::select(Year, Station, annsal_ppt, anntemp_c) %>% 
       gather(key = "env_var", "scaled_value", -c(Year, Station)), 
       aes(x=as.numeric(Year)+2000, y=scaled_value)) + 
  geom_line(aes(color=Station, linetype=Station), cex=1.5) +
  scale_x_continuous(breaks = c(2001, 2005, 2010, 2015, 2018)) +
  scale_linetype_manual(values=c("solid", "dotted", "solid", "dotted")) +
  scale_color_manual(values = c("#000000", "#000000", "#727272", "#727272")) + 
  labs(x="", y="Scaled value, mu=0, sd=1") +
  facet_wrap(~env_var, labeller = as_labeller(c(`annsal_ppt` = "Salinity", `anntemp_c` = "Water Temperature"))) +
  theme_bw() + 
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), 
        text=element_text(family="Times New Roman", size=12), 
        axis.text.x = element_text(angle = 35, hjust = 1),
        strip.background = element_blank()) # could also do element_rect(fill="white")
#ggsave("plotexports/Fig_envvar.png", dpi = 300, width = 7.5, height = 5)




summary(lm(annsal_ppt ~ as.numeric(Year) + Station, data = pru.env.ann))
summary(lm(anntemp_c ~ as.numeric(Year) + Station, data = pru.env.ann))
summary(lm(annwindspeed_kph ~ as.numeric(Year), data = pru.env.ann))
summary(lm(anndisch_cfs ~ as.numeric(Year), data = pru.env.ann))
summary(lm(annwinddir_ew ~ as.numeric(Year), data = pru.env.ann))


```


```{r envvar}
pru.env.biwk %>% #group_by(Year, biweekly, Station) %>% 
  summarise(min =mean(biwkmeanspeed_kph))
min(pru.env.biwk$biwkmeanspeed_kph)
max(pru.env.biwk$biwkmeanspeed_kph)
mean(pru.env.biwk$biwkmeanspeed_kph)

mean(pru.env.biwk$biwkmeandir)

pru.env.biwk %>% ungroup() %>%
  summarise(mean = ((circ.mean(2*pi*na.omit(biwkmeandir)/360))*(360 / (2*pi))) %%360)

min(pru.env.biwk$meandisch_cfs)
max(pru.env.biwk$meandisch_cfs)
mean(pru.env.biwk$meandisch_cfs)

min(pru.env.biwk$Temp_Top, na.rm = TRUE)
max(pru.env.biwk$Temp_Top, na.rm = TRUE)
mean(pru.env.biwk$Temp_Top, na.rm = TRUE)

min(pru.env.biwk$Salin_Top, na.rm = TRUE)
max(pru.env.biwk$Salin_Top, na.rm = TRUE)
mean(pru.env.biwk$Salin_Top, na.rm = TRUE)

```
